### ISSUE TITLE
Change Bindings API

### ISSUE THREAD

**Issue by RobLoach** [RobLoach/node-raylib#11]
Node-Addon-API is great, but there could be better alternatives out there to make things easier....

Name | Description | Pull Request
-------| --- | ------
[Node Addon API](https://www.npmjs.com/package/node-addon-api) | This is what its currently using. Unfortunately I don't think it'll build the Emscripten bindings. | N/A
[Emscripten](https://kripken.github.io/emscripten-site/) | While it does work on the web, and you can make raylib calls from JavaScript, the bindings won't work on the Desktop. | https://github.com/RobLoach/node-raylib/pull/14
[NBind](https://github.com/charto/nbind) | Got this working for the desktop, but requires a bit more work, since structs don't pass correctly. [nbind-example-universal](https://github.com/charto/nbind-example-universal) | #13
[fastcall](https://github.com/cmake-js/fastcall) | Looks like a library that makes it easy to bind | --

**Comment by konsumer** [comment]
fastcall uses node ffi lib, which is another option, directly. There is related issue over [here](https://github.com/Koromix/luigi/issues/1) to make dynlib calls faster than ffi lib. They seem to have nice performance tests in place, and have similar goals (wrapping raylib in native.)
