### ISSUE TITLE
Tiled

### ISSUE THREAD

**Issue by konsumer** [RobLoach/node-raylib#131]
I worked on [tiled](https://www.mapeditor.org/) a bit (I added stuff to the javascript plugin API), and separately, made [tiled-kaboom](https://www.npmjs.com/package/tiled-kaboom).

I could see a very useful addon being a loader for those tilemaps. Not sure if that really fits in the scope of this project, but it would be pretty cool to make a game using tilemaps directly. I could see this being a separate, but included addon (see #130)

**Comment by RobLoach** [comment]
Very cool! I think it could live as a new package in its own repo. Like named `node-raylib-tiled` or something?

**Comment by twuky** [comment]
ive also worked on a loader / renderer for [ldtk](https://ldtk.io/) tilemaps. though before i publish i'd like to have it work as a shader to render in a single draw call. i agree things like that should probably be individual packages though. 

i think it would be appreciated though if useful libraries built for node-raylib were linked off of readme.md, or their own page. just allow people to PR into it with their additions

**Comment by konsumer** [comment]
I love that idea. [ldtk](https://ldtk.io/) also seems really cool. I totally agree it's out of scope for node-raylib, but a section in the README would help people promote related projects, which would be great.

**Comment by konsumer** [comment]
I will close this for now, in favor of #136
