### ISSUE TITLE
"awesome projects"

### ISSUE THREAD

**Issue by konsumer** [RobLoach/node-raylib#136]
We should somehow reference awesome related projects, to give our users a nice list of libs they can use with node-raylib. 

It could go directly in the README, wiki, or even a separate project with a big list (like all the other awesome-whatever projects.) This way people can PR to add their project to the list.

Related: #131

**Comment by twuky** [comment]
im not quite ready to add anything to it yet, but if someone does have something made with node-raylib to share, lets start it.
if its in its own file or repo, lets still link to it from the readme. 
ideally its somewhere quickly accessible to anyone new, so they can get a grasp of what is and isnt out there and users dont end up reinventing the wheel on things like tilemap renderers etc

**Comment by RobLoach** [comment]
Could be in the README. An Extras section? Alternatively we could open up the Wiki for the project.

**Comment by RobLoach** [comment]
https://github.com/RobLoach/node-raylib/pull/143
