### ISSUE TITLE
Rename to raylib-js

### ISSUE THREAD

**Issue by RobLoach** [RobLoach/node-raylib#15]
**raylib-js**

Will match the other raylib naming conventions :smile:

**Comment by raysan5** [comment]
Why? I mean, `node-raylib` feels ok to me... and I understand the binding requires Node.js, right?

**Comment by RobLoach** [comment]
Been thinking you may have been right about [questioning `node-raylib`](https://github.com/RobLoach/node-raylib/issues/9#issuecomment-456220642) as a name for two reasons....

1. ["Usually, raylib bindings follow the convention: raylib-{language}"](https://github.com/raysan5/raylib/blob/master/CONTRIBUTING.md#raylib-bindings)
2. Would like to allow using Raylib through JavaScript on the desktop (Node.js), and on the web (emscripten).

While it is Node.js for the desktop, it's technically not Node.js on the web through emscripten. Both cases, however, use JavaScript. So `raylib-js` might make sense for both, and it would match the conventions of the other names.....

Still trying to figure out how it can be built for both cases though. Tried in three build systems.....

1. [Node Addon API](https://www.npmjs.com/package/node-addon-api): This is what its currently using. Unfortunately I don't think it'll build the Emscripten bindings.
2. [Emscripten](https://github.com/RobLoach/node-raylib/pull/14): While it does work on the web, and you can make raylib calls from JavaScript, the bindings won't work on the Desktop.
3. [NBind](https://github.com/RobLoach/node-raylib/pull/13): Got this working for the desktop, but requires a bit more work, since structs don't pass correctly.

Again, the name change all depends on if the bindings for both desktop and web work. Then, `raylib-js` makes sense... Until then, `node-raylib` will do. :+1:

**Comment by RobLoach** [comment]
Would like to rename the name in the package.json to `raylib` so that it becomes...

```
const r = require('raylib')
```
