### ISSUE TITLE
PLATFORM_DRM for installation in RPI

### ISSUE THREAD

**Issue by JesperNaarttijarvi** [RobLoach/node-raylib#166]
Hi,

Similar to issue #86 and #91 I want to compile the npm package with the option PLATFORM_DRM for raylib, so I can run it without X-11.

I can get the original raylib to work just fine on minimal install without X11, with the flag "PLATFORM=PLATFORM_DRM"

I cant get #86 and #91 to work for 4.2, is there an easy way to add the flag "PLATFORM=PLATFORM_DRM" when installing the package?

**Comment by konsumer** [comment]
#158 has some info on setting custom cmake flags, but I think you can also set `PLATFORM=PLATFORM_DRM` as an env-var to trigger the same behaviour.

On mac/lunix:

```
export PLATFORM=PLATFORM_DRM
```

or in cmake, in the node-raylib dir:

```
npm run compile -- --CDPLATFORM DRM
```

This is untested (I'm on a mac, and don't know where my pi for testing is) but let me know if you have issues.

**Comment by konsumer** [comment]
I usually manually build the node release for pi/mac-arm, but I think there have been a couple releases without it. Github actions can't build for arm, so we have to do some tricky stuff to get it working. Looks like [our automated arm-builds are currently failing](https://github.com/RobLoach/node-raylib/actions/runs/2922163801).

**Comment by JesperNaarttijarvi** [comment]
Thanks for the fast response, but sadly none of the tips worked for me. 

I looked at #158 before and tried to run `npm run compile -- --CDPLATFORM=DRM` in the node package, it did not work, same fault as before.


Deleted the old installation files, set env-var and then installing raylib manually. Also didnt work.
````
rm -rf ./node_modules
export PLATFORM=PLATFORM_DRM
npm i raylib
````


Problems:

`node app.js `
yields
`````
INFO: Initializing raylib 4.2
INFO: Supported raylib modules:
INFO:     > rcore:..... loaded (mandatory)
INFO:     > rlgl:...... loaded (mandatory)
INFO:     > rshapes:... loaded (optional)
INFO:     > rtextures:. loaded (optional)
INFO:     > rtext:..... loaded (optional)
INFO:     > rmodels:... loaded (optional)
INFO:     > raudio:.... loaded (optional)
WARNING: GLFW: Error: 65544 Description: X11: The DISPLAY environment variable is missing
WARNING: GLFW: Failed to initialize GLFW
FATAL: Failed to initialize Graphic Device
`````

`DISPLAY=:0 node app.js  `
yields
`````
INFO: Initializing raylib 4.2
INFO: Supported raylib modules:
INFO:     > rcore:..... loaded (mandatory)
INFO:     > rlgl:...... loaded (mandatory)
INFO:     > rshapes:... loaded (optional)
INFO:     > rtextures:. loaded (optional)
INFO:     > rtext:..... loaded (optional)
INFO:     > rmodels:... loaded (optional)
INFO:     > raudio:.... loaded (optional)
WARNING: GLFW: Error: 65544 Description: X11: Failed to open display :0
WARNING: GLFW: Failed to initialize GLFW
FATAL: Failed to initialize Graphic Device
`````
 



Packages i had to install to run npm i raylib:

````
libxrandr-dev
libxinerama-dev
libxcursor-dev
libxi-dev

````

The only packages I've installed before this is `libdrm-dev libegl1-mesa-dev libgles2-mesa-dev libgbm-dev` as recommended by Raylibs website.

**Comment by JesperNaarttijarvi** [comment]
user: `~/.../raylib/node_modules/raylib $ npm run compile -- --CDPLATFORM=DRM`

``````
> raylib@0.12.0 precompile
> npm i --no-save node-addon-api cmake-js


up to date, audited 677 packages in 6s

118 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

> raylib@0.12.0 compile
> cmake-js compile "--CDPLATFORM=DRM"

info TOOL Using Unix Makefiles generator.
info CMD BUILD
info RUN [
info RUN   'cmake',
info RUN   '--build',
info RUN   '/home/itos/passage/raylib/node_modules/raylib/build',
info RUN   '--config',
info RUN   'Release'
info RUN ]
[ 62%] Built target glfw
[ 92%] Built target raylib
[100%] Built target node-raylib
``````

**Comment by konsumer** [comment]
hmm, lemme see if I can get a pi setup for building, and I will build you one for release. I can't quite remember what is needed, but I think there is some simple cmake thing that will enable the flag (it used to be on by defaullt.)

**Comment by konsumer** [comment]
Sidenote: @twuky is working on fixing the build, too, so that might help things.

**Comment by konsumer** [comment]
Looking at [cmakejs](https://github.com/cmake-js/cmake-js) docs, I think it should be :
```
--CDPLATFORM=DRM
```

So I am wondering if maybe the script doesn't like it. Try this in node-raylib dir:

```
cmake-js compile --CDPLATFORM=DRM
```

I can't seem to remember the env-var format, but I think that is an easier way to set same thing. I will try to figure it out.

**Comment by JesperNaarttijarvi** [comment]
Now its running with the correct flag. Got an other error, looking into it now.
`````
user@user100:~/rep/raylib/node_modules/raylib $ cmake-js compile --CDPLATFORM=DRM
info TOOL Using Unix Makefiles generator.
info CMD BUILD
info RUN [
info RUN   'cmake',
info RUN   '--build',
info RUN   '/home/user/rep/raylib/node_modules/raylib/build',
info RUN   '--config',
info RUN   'Release'
info RUN ]
[ 62%] Built target glfw
[ 92%] Built target raylib
Scanning dependencies of target node-raylib
[ 96%] Building CXX object CMakeFiles/node-raylib.dir/src/generated/node-raylib.cc.o
/home/user/rep/raylib/node_modules/raylib/src/generated/node-raylib.cc:4:10: fatal error: napi.h: No such file or directory
    4 | #include <napi.h>
      |          ^~~~~~~~
compilation terminated.
gmake[2]: *** [CMakeFiles/node-raylib.dir/build.make:82: CMakeFiles/node-raylib.dir/src/generated/node-raylib.cc.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:172: CMakeFiles/node-raylib.dir/all] Error 2
gmake: *** [Makefile:171: all] Error 2
info REP Build has been failed, trying to do a full rebuild.
info CMD CLEAN
info RUN [
info RUN   'cmake',
info RUN   '-E',
info RUN   'remove_directory',
info RUN   '/home/user/rep/raylib/node_modules/raylib/build'
info RUN ]
info CMD CONFIGURE
info RUN [
info RUN   'cmake',
info RUN   '/home/user/rep/raylib/node_modules/raylib',
info RUN   '--no-warn-unused-cli',
info RUN   '-G',
info RUN   'Unix Makefiles',
info RUN   '-DCMAKE_JS_VERSION=undefined',
info RUN   '-DCMAKE_BUILD_TYPE=Release',
info RUN   '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/user/rep/raylib/node_modules/raylib/build/Release',
info RUN   '-DCMAKE_MSVC_RUNTIME_LIBRARY=MultiThreaded$<$<CONFIG:Debug>:Debug>',
info RUN   '-DCMAKE_JS_INC=/home/user/.cmake-js/node-arm/v17.4.0/include/node',
info RUN   '-DCMAKE_JS_SRC=',
info RUN   '-DNODE_RUNTIME=node',
info RUN   '-DNODE_RUNTIMEVERSION=17.4.0',
info RUN   '-DNODE_ARCH=arm',
info RUN   '-DPLATFORM=DRM',
info RUN   '-DCMAKE_JS_LIB=',
info RUN   '-DCMAKE_CXX_FLAGS=-DBUILDING_NODE_EXTENSION'
info RUN ]
Not searching for unused variables given on the command line.
-- The C compiler identification is GNU 10.2.1
-- The CXX compiler identification is GNU 10.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Populating raylib
-- Configuring done
-- Generating done
-- Build files have been written to: /home/user/rep/raylib/node_modules/raylib/build/_deps/raylib-subbuild
Scanning dependencies of target raylib-populate
[ 11%] Creating directories for 'raylib-populate'
[ 22%] Performing download step (git clone) for 'raylib-populate'
Cloning into 'raylib-src'...
Note: switching to '4.2.0'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at bf2ad9d P A I N
[ 33%] Performing update step for 'raylib-populate'
[ 44%] No patch step for 'raylib-populate'
[ 55%] No configure step for 'raylib-populate'
[ 66%] No build step for 'raylib-populate'
[ 77%] No install step for 'raylib-populate'
[ 88%] No test step for 'raylib-populate'
[100%] Completed 'raylib-populate'
[100%] Built target raylib-populate
-- Performing Test COMPILER_HAS_THOSE_TOGGLES
-- Performing Test COMPILER_HAS_THOSE_TOGGLES - Success
-- Testing if -Werror=pointer-arith can be used -- compiles
-- Testing if -Werror=implicit-function-declaration can be used -- compiles
-- Testing if -fno-strict-aliasing can be used -- compiles
-- No GLFW required on PLATFORM_DRM
-- Audio Backend: miniaudio
-- Building raylib static library
-- Generated build type: Release
-- Compiling with the flags:
--   PLATFORM=PLATFORM_DRM
--   GRAPHICS=GRAPHICS_API_OPENGL_ES2
-- Configuring done
-- Generating done
-- Build files have been written to: /home/user/rep/raylib/node_modules/raylib/build
info CMD BUILD
info RUN [
info RUN   'cmake',
info RUN   '--build',
info RUN   '/home/user/rep/raylib/node_modules/raylib/build',
info RUN   '--config',
info RUN   'Release'
info RUN ]
Scanning dependencies of target raylib
[ 10%] Building C object _deps/raylib-build/raylib/CMakeFiles/raylib.dir/rcore.c.o
[ 20%] Building C object _deps/raylib-build/raylib/CMakeFiles/raylib.dir/rmodels.c.o
[ 30%] Building C object _deps/raylib-build/raylib/CMakeFiles/raylib.dir/rshapes.c.o
[ 40%] Building C object _deps/raylib-build/raylib/CMakeFiles/raylib.dir/rtext.c.o
[ 50%] Building C object _deps/raylib-build/raylib/CMakeFiles/raylib.dir/rtextures.c.o
[ 60%] Building C object _deps/raylib-build/raylib/CMakeFiles/raylib.dir/utils.c.o
[ 70%] Building C object _deps/raylib-build/raylib/CMakeFiles/raylib.dir/raudio.c.o
[ 80%] Linking C static library libraylib.a
[ 80%] Built target raylib
Scanning dependencies of target node-raylib
[ 90%] Building CXX object CMakeFiles/node-raylib.dir/src/generated/node-raylib.cc.o
/home/user/rep/raylib/node_modules/raylib/src/generated/node-raylib.cc:4:10: fatal error: napi.h: No such file or directory
    4 | #include <napi.h>
      |          ^~~~~~~~
compilation terminated.
gmake[2]: *** [CMakeFiles/node-raylib.dir/build.make:82: CMakeFiles/node-raylib.dir/src/generated/node-raylib.cc.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:133: CMakeFiles/node-raylib.dir/all] Error 2
gmake: *** [Makefile:171: all] Error 2
ERR! OMG Process terminated: 2
`````

**Comment by konsumer** [comment]
napi missing means it doesn't have all the dev-deps installed. This was a bit of a catch-22 I remember from building DRM with `npm i` that an env-var helps with. It will take me a bit, but I will setup a pi for testing, here, and try to help figure it out.

**Comment by twuky** [comment]
we don't include node-addon-api or cmake-js as deps or devdeps any more, i think you need to install those both with --no-save

**Comment by twuky** [comment]
we don't include node-addon-api or cmake-js as deps or devdeps any more, i think you need to install those both with --no-save

**Comment by konsumer** [comment]
ah, yeh, I think the preinstall stuff does that, so "normal" users don't have to download a bunch of dev-deps.

**Comment by JesperNaarttijarvi** [comment]
Installed node-addon-api, still gets an error. Its doing a full rebuild now so will see soon what's crashing.

**Comment by twuky** [comment]
okay, I've got CI working on building on arm with DRM enabled and can reproduce your error. It seems like it has something to do with compiler differences, and structs with default values? I'm not a C expert, so it may take a bit to find out whats going on. it sounds like it may be platform specific to gmake?

**Comment by twuky** [comment]
looks like this struct uses different values for opengl ES2.0 on drm. so we need to construct it like this to  match:

```c
// exception for this constructor, which has different input depending on platform
inline rlVertexBuffer rlVertexBufferFromValue(const Napi::CallbackInfo& info, int index) {
  return {
     intFromValue(info, index + 0),
     (float *) pointerFromValue(info, index + 1),
     (float *) pointerFromValue(info, index + 2),
     (unsigned char *) pointerFromValue(info, index + 3),
      #if defined(GRAPHICS_API_OPENGL_11) || defined(GRAPHICS_API_OPENGL_33)
        (unsigned int *) pointerFromValue(info, index + 4),      // Vertex indices (in case vertex data comes indexed) (6 indices per quad)
      #endif
      #if defined(GRAPHICS_API_OPENGL_ES2)
        (unsigned short *) pointerFromValue(info, index + 4),    // Vertex indices (in case vertex data comes indexed) (6 indices per quad)
      #endif
     unsignedintFromValue(info, index + 5),
     (unsigned int) pointerFromValue(info, index + 6)
  };
}
```

pushing a change to the generator that includes this and we'll see how it builds.

**Comment by twuky** [comment]
@JesperNaarttijarvi It looks like CI builds of DRM raylib are completing succesfully. I haven't published anything to npm because I don't have a system to test, but if you want to try you can use the prebuilt copies at https://github.com/RobLoach/node-raylib/releases/tag/v0.12.5 - either replace node-raylib.node in `build/Release` or you can require the .node directly and use raylib functions, though you won't have built in constant colors, so you'll have to create those as objects yourself.

Let me know if these work and we can figure out how to integrate them better into the install process. 
I was thinking that whenever an ARM target installs, it will grab both the normal and DRM versions, and users will instead `import * as rl from 'raylib/drm'` to use that version.

**Comment by JesperNaarttijarvi** [comment]
It worked, and now we got an other error. Maybe not related. 

Currently installing original raylib and compiling, to see if we get the same error.

``````
INFO: Initializing raylib 4.2
INFO: Supported raylib modules:
INFO:     > rcore:..... loaded (mandatory)
INFO:     > rlgl:...... loaded (mandatory)
INFO:     > rshapes:... loaded (optional)
INFO:     > rtextures:. loaded (optional)
INFO:     > rtext:..... loaded (optional)
INFO:     > rmodels:... loaded (optional)
INFO:     > raudio:.... loaded (optional)
INFO: DISPLAY: No graphic card set, trying platform-gpu-card
WARNING: DISPLAY: Failed to find a suitable DRM connector mode
FATAL: Failed to initialize Graphic Device
``````

**Comment by JesperNaarttijarvi** [comment]
Problem was the resolution i set was too high, lowering the resolution solved the problem.

**Comment by konsumer** [comment]
> Problem was the resolution i set was too high, lowering the resolution solved the problem.

I had this problem too!

I thought for sure arm handhelds were not working, but it turned out to just be the resolution.

**Comment by JesperNaarttijarvi** [comment]
The easiest for me would definitely be to change the import to drm, but we dont run raylib cross-platform which might cause problems. 

But on second thought, the people running drm probably have a little bit of knowledge about installations, so having flags is probably not a problem either. But i dont want to download the package twice and recompile it several times, because that takes time.

A seperate npm would also work, but then the gap in version handling between the two repos might grow apart?

**Comment by twuky** [comment]
Well now that CI is properly building both versions of the linux-arm raylib, users shouldn't have to compile anything unless there are some additional flags they want to set. When you install from npm, we run a postinstall script that checks the Releases on github for a version of raylib compatible with the system. In the case of ARM, I've changed it so it downloads both the drm and nondrm version. 
It should only have to build raylib now if you are on an unsupported platform by our prebuilt native addons. For instance we don't have macos-arm (M1,M2,etc) set up in CI. but sometimes we add those to the releases manually.

I think for now I'll work on having a secondary import for DRM users within this package

**Comment by konsumer** [comment]
> But i dont want to download the package twice and recompile it several times, because that takes time.

Yeh, the builds will be done for you, so when you `npm i` it, it will download (the pre-built) and setup the drm version. The reason you have to build it now is because our CI auto-builds were failing for arm, which @twuky just fixed.

> I think for now I'll work on having a secondary import for DRM users within this package

I am all for this, but also I think just setting it to build like that for linux-arm is ok, too. Like I said, pretty much all linux arm can benefit from DRM build, and the only reason not to do it on linux x86_64 is that it's possible the X drivers are better than the DRM, but it should mostly work there too. It used to be that pi had a special build, that used these special pi framebuffer drivers vs X/DRM (which are both linux standards), but but now it's just standard DRM which most linux users have, and latest pi os uses DRM, and also most handheld arm devices, even if they don't have X installed.

**Comment by JesperNaarttijarvi** [comment]
Reinstalled all node_modules and changed raylib-node to npm i https://github.com/RobLoach/node-raylib.

First problem:
```
import * as rl from 'raylib/drm'

ERROR 

Error [ERR_UNSUPPORTED_DIR_IMPORT]: Directory import '/home/user/rep/raylib/node_modules/raylib/drm' is not supported resolving ES modules imported from /home/user/rep/raylib/app.js
Did you mean to import raylib/node_modules/raylib/drm/index.js?
```

After updating to import index.js

```
user@user100:~/rep/raylib $ node app.js 
node:internal/modules/cjs/loader:933
  const err = new Error(message);
              ^

Error: Cannot find module '../../build/Release/node-raylib-drm.node'
Require stack:
- /home/user/rep/raylib/node_modules/raylib/src/generated/node-raylib-drm.js
- /home/user/rep/raylib/node_modules/raylib/drm/index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/user/rep/raylib/node_modules/raylib/src/generated/node-raylib-drm.js:10:11)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/user/rep/raylib/node_modules/raylib/src/generated/node-raylib-drm.js',
    '/home/user/rep/raylib/node_modules/raylib/drm/index.js'
  ]
}
```




```
user@user100:~/rep/raylib $ ls node_modules/raylib/build/Release/
node-raylib.node
```

**Comment by konsumer** [comment]
not sure what the prob is, but this should fix:
```
wget https://github.com/RobLoach/node-raylib/releases/download/v0.13.0/node-raylib-linux-arm-drm.node -o node_modules/raylib/build/Release/node-raylib-drm.node
```

**Comment by twuky** [comment]
Ohhh, I missed that postinstall calls process.exit() when it downloads the first prebuilt, so it was never grabbing the DRM version. Reversed the order so it tries for DRM first, and doesn't exit prematurely. I've also updated the docs in readme about the index.js issue.

This should be everything it needs now!

**Comment by konsumer** [comment]
It is going to have problems in mjs anyway, due to the `require`s. I am not sure of a good way to resolve that, other than multiple published libraries (each with different entrypoint) or putting it all int eh same file. maybe something like this?

```js
import { getDrm } from 'raylib'
const raylib = await getDrm()
```

**Comment by konsumer** [comment]
Yep, I think that would be a good step in the right direction. I don't use typescript myself, but it seems a bit jenky to generate the typedefs separate from the code. It's just what it outputs, so I really don't care if it's in typescript, as long as ES6 is exported by module (in build step before publish.)
