### ISSUE TITLE
Fix CameraUpdate() for Object References

### ISSUE THREAD

**Issue by robertoEpe** [RobLoach/node-raylib#30]
While transfering the example core_world_screen.c into javascript in my machine, the call to r.CameraUptate(camera) crashes the program, without any error or anything.

**Comment by RobLoach** [comment]
You're right... Looks like `CameraUpdate()` takes a `Camera*`, not just a `Camera` object.

**Comment by robertoEpe** [comment]
Yes, I have tested the updateCamera branch, the reason it disappear is because you branched before adding the default parameters in the functions Vector3 and Vector2. Just add the parameters and it would not crash and will show the cube.

On the other hand and this may be another issue `r.SetCameraMode(camera, r.CAMERA_FREE);` doesn't do anything, if you do instead  `r.SetCameraMode(camera, r.CAMERA_ORBITAL);` fails to rotate as it should

**Comment by RobLoach** [comment]
Merged master in! Working! Good find....

Another concern I have is this...

```
console.log(camera)
r.UpdateCamera(camera);          // Update camera
console.log(camera)
```

Both console.log() result with this...
```
{ position: { x: 10, y: 10, z: 10 },
  target: { x: 0, y: 0, z: 0 },
  up: { x: 0, y: 1, z: 0 },
  fovy: 45,
  type: 0 }
```

Since we're mocking the `Camera*`, it's not actually updating the camera.

**Comment by RobLoach** [comment]
Added [`examples/core/core_3d_camera_first_person.js`](https://github.com/RobLoach/node-raylib/blob/updatecamera/examples/core/core_3d_camera_first_person.js).

The camera doesn't actually move. We'll have to figure out how to handle object pointers properly.

**Comment by RobLoach** [comment]
Merged the PR since it's much better than just crashing the program. Can rework this issue.

**Comment by RobLoach** [comment]
I think this is fixed now.
