### ISSUE TITLE
3.0 support ?

### ISSUE THREAD

**Issue by Guevara-chan** [RobLoach/node-raylib#46]
It seems like new major release of raylib was recently released, so `node-raylib` badly requires updating.
That project wasn't abandoned, I hope ?

**Comment by raysan5** [comment]
Wait, raylib 3.0 has not been released yet, I'm still working on it

**Comment by Guevara-chan** [comment]
Seriously ? Your own manual states v3.0 already: https://www.raylib.com/cheatsheet/cheatsheet.html

**Comment by raysan5** [comment]
@Guevara-chan yeah, I'm working on it and updating all required things: https://github.com/raysan5/raylib/issues/1084

But not finished yet, too many things to do. Official release will be announced when everything gets ready.

**Comment by RobLoach** [comment]
Updated to the latest raylib. There's likely still some methods missing, would love your help on finding those :wink:

**Comment by raysan5** [comment]
@RobLoach Just added two new functions yesterday: `LoadFileData()` and `SaveFileData()`.

Also renamed two functions: 
  `StorageLoadValue()` -> `LoadStorageValue()`
  `StorageSaveValue()` -> `SaveStorageValue()`

**Comment by RobLoach** [comment]
> added two new functions yesterday: LoadFileData() and SaveFileData().

Nice! I'll add those ones...

> Also renamed two functions:

:smile: 
https://github.com/RobLoach/node-raylib/commit/1605bbc27aa0c9784c8d20987fb231e8a34dca55#diff-bf75da96246b1b40dcd6f1edb71ad474

**Comment by RobLoach** [comment]
There's the odd update coming through. Going to keep this open until 3.0 is released and node-raylib is updated.
