### ISSUE TITLE
Window Hangs On Launch

### ISSUE THREAD

**Issue by VeXan39231** [RobLoach/node-raylib#84]
For about 30 seconds after running node index.js and opening the window, it freezes for about 30 seconds. I'm not sure if this is just a node-raylib thing, but it happens no matter what program is being run. I haven't found anything online about this problem, I was hoping this would be a good place to start.

**Comment by RobLoach** [comment]
Windows? Mind running in verbose and sharing logs?

**Comment by VeXan39231** [comment]
Super strange, but the issue managed itself. You can close this issue ticket :) Sorry for your time

**Comment by RobLoach** [comment]
Glad it worked!!!
