### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by RobLoach** [RobLoach/node-raylib#9]
Add a kewl logo .biz.

**Comment by raysan5** [comment]
I can create a logo for it, just wondering... why is called `node-raylib` instead of `raylib-node`, is it a naming convention for Node.js libraries?

**Comment by RobLoach** [comment]
> I can create a logo for it, just wondering

That'd be awesome! No rush though, this is still extremely early. Just sticking "node" beside "raylib" should do it, like what you did with [the lua one](https://github.com/raysan5/raylib-lua/blob/master/logo/raylib-lua_256x256.png) :wink: 

Potentially using the Node.js brand green?? I think it's like `#669f64`? https://nodejs.org/en/about/resources/

> is it a naming convention for Node.js libraries?

Correct... The majority of binding related modules are prefixed with `node-`. One example is [node-sass](https://www.npmjs.com/package/node-sass).

**Comment by RobLoach** [comment]
![node-raylib Logo](https://raw.githubusercontent.com/RobLoach/node-raylib/master/logo/raylib-node_256x256.png)

https://github.com/RobLoach/node-raylib/blob/master/examples/shapes/shapes_logo_raylib.js

**Comment by raysan5** [comment]
@RobLoach Excuse me, I completely forget about it... 😓

Anyway, I love the logo you created!!! 😄

**Comment by RobLoach** [comment]
Used the example so it was super easy!!!! :laughing:
